/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.strawberry.organizer;

import org.junit.Test;
import static org.junit.Assert.*;

public class OrganizerRunnerTest {
    @Test public void testAppHasAGreeting() {
        OrganizerRunner classUnderTest = new OrganizerRunner();
        assertNotNull("app should have a greeting", "dvdv");
    }
}
